### ISSUE TITLE
Repository not working with Node 8.10.0

### ISSUE THREAD

**Issue by MarvinKlemp** [jasontalon/supervisely-to-darknet-dataset-converter#2]
`node index` => error: `TypeError: _.join(...).trimEnd is not a function`
